# Configuration for the module
baseURL: 'https://github.com/agsayyed/hb-ags-module-template'
title: 'hb-ags-template'
description: 'This template is used to create modules based upon hbstack modules with vendor name ags'

module:
  name: hb-module-template
  version: 1.0.0
  description: A template for HB modules.
  hugoVersion:
    min: '0.110.0'

module.imports:
#  - path: "github.com/hugomods/bootstrap"
